name: STREAMLINK LIVE

# Controls when the action will run. 
on:
  schedule:
    - cron: "*/41 * * * *"

  
  
  push:
    branches:
    - master
    - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository using a token
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{github.ref}}
          token: ${{secrets.GITHUB_TOKEN}}
      
      # Configure Git
      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      
      # Installing yt-dlp
      - name: Install yt-dlp
        run: |
          wget https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -O /usr/local/bin/yt-dlp
          chmod a+rx /usr/local/bin/yt-dlp
      
      # Installing youtube-dl
      - name: Install youtube-dl
        run: |
          wget https://yt-dl.org/downloads/latest/youtube-dl -O /usr/local/bin/youtube-dl
          chmod a+rx /usr/local/bin/youtube-dl    
          youtube-dl -U
      
      # Installing streamlink
      - name: Install streamlink
        run: |
          pip install --user --upgrade streamlink   
          
      # Installing dependencies
      - name: Install dependencies
        run: |
          pip install youtube-dl 
          pip install requests 
          pip install beautifulsoup4 
          pip install fastapi 
          pip install uvicorn 
          pip install schedule
          pip install selenium
          pip install datetime
          pip install pytz
      
      - name: Get BBMEXICOUSA.ts
        run: |
         touch ./BBMEXICOUSA.ts
         sudo cat >./BBMEXICOUSA.ts <<EOL
     
         $(streamlink --force --hls-duration 00:00:15 --output "BBMEXICOUSA.ts" https://www.youtube.com/@TelemundoEntretenimiento/live best)
         $(streamlink --force --hls-duration 00:00:15 --output "CBSNEWS.ts" https://www.cbsnews.com/live/ best)
         $(streamlink --force --hls-duration 00:00:15 --output "CNNPORTUGAL.ts" https://tviplayer.iol.pt/direto/CNN best best)
 
 
      - name: Get BBMEXICOUSA2.ts
        run: |


         now = datetime.datetime.now(pytz.timezone("America/Sao_Paulo"))
         tempo = now.strftime('%m%d_%H%M%S')
         tempo2 = now.strftime('-%Y')

         filename =   tempo + "BBMEXICOUSA_" + tempo2 + ".ts"

         touch ./"BBMEXICOUSA.ts
         sudo cat >./BBMEXICOUSA.ts <<EOL
         $(streamlink --force --hls-duration 00:00:15 --output "${filename}" https://www.youtube.com/@TelemundoEntretenimiento/live best)

      
      - name: Get LISTA4.m3u8
        run: |
         touch ./lista2str.m3u
         sudo cat >./lista2str.m3u <<EOL      
         
         
         #EXTM3U
         #EXT-X-VERSION:3
         #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
         #EXTINF:-1 tvg-id="$(yt-dlp --get-title https://www.youtube.com/watch?v=EeQnkxY9QFs)" group-title="Reality Show'S Live" group-title="CNN's" tvg-logo="$(yt-dlp --get-thumbnail https://www.youtube.com/watch?v=EeQnkxY9QFs)", YOUTUBEAOVIVO - $(yt-dlp --get-title https://www.youtube.com/watch?v=EeQnkxY9QFs)
         $(streamlink --url --default-stream  --stream-url  https://www.youtube.com/@TelemundoEntretenimiento/live best)
         
         
      
      - name: Add Changes to Git
        run: |
          git add -A
          ls -la 
          
      # Commit and Push changes
      - name: Commit & Push
        run: |
          git commit -m "links atualizados"
          git push
